In [64]:
'''Dimensionality Reduction (Bank Data)''' 

# Import Libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [65]:
os.getcwd()

'C:\\Users\\HP\\Downloads\\Batch 93 Day34'

In [66]:
# Load Data Set

os.chdir('C:\\Users\\HP\\Downloads\\Batch 93 Day34\\')

In [67]:
df=pd.read_csv('Bank Data Dimension Reduction.csv')
print(df)

     Index  Interest  Credit  Gender  Previous  Duration Churn
0        0   17546.0       1     0.0       0.0      48.0    NO
1        1   30085.1       3     1.0       1.0      40.0   YES
2        2   16575.4       0     0.0       1.0      51.0   YES
3        3   20375.4       3     0.0       0.0      23.0   YES
4        4   50576.3       0     0.0       0.0      57.0    NO
..     ...       ...     ...     ...       ...       ...   ...
595    595   47025.0       2     0.0       1.0       NaN   YES
596    596    9672.3       0     0.0       1.0       NaN   YES
597    597   15976.3       0     0.0       1.0       NaN    NO
598    598   14711.8       0     1.0       0.0      29.0    NO
599    599   26671.6       0     1.0       1.0      38.0   YES

[600 rows x 7 columns]


In [68]:
# Data Check

print(df.isna().sum())

Index        0
Interest    68
Credit       0
Gender      21
Previous     7
Duration    70
Churn        0
dtype: int64


In [69]:
print(df.notna().sum())

Index       600
Interest    532
Credit      600
Gender      579
Previous    593
Duration    530
Churn       600
dtype: int64


In [70]:
# Data Type

print(df.dtypes)

Index         int64
Interest    float64
Credit        int64
Gender      float64
Previous    float64
Duration    float64
Churn        object
dtype: object


In [71]:
# Fill missing Value Gender - Fill with Maximum Repeated value (Fill with 0)

print(df.groupby('Gender').size())

Gender
0.0    290
1.0    289
dtype: int64


In [72]:
df['Gender']=df['Gender'].fillna(0)
print()
print(df.groupby('Gender').size())


Gender
0.0    311
1.0    289
dtype: int64


In [73]:
# Fill missing Value Previous

print(df.groupby('Previous').size())


Previous
0.0    302
1.0    291
dtype: int64


In [74]:
df['Previous']=df['Previous'].fillna(0)

In [75]:
print(df.groupby('Previous').size())


Previous
0.0    309
1.0    291
dtype: int64


In [76]:
print(df.isna().sum())

Index        0
Interest    68
Credit       0
Gender       0
Previous     0
Duration    70
Churn        0
dtype: int64


In [77]:
# Fill missing Value Interest Rate

print(df.isna().sum())

Index        0
Interest    68
Credit       0
Gender       0
Previous     0
Duration    70
Churn        0
dtype: int64


In [78]:
df['Interest'].mean()

27630.171616541356

In [79]:
df['Interest'].fillna(df['Interest'].mean(),inplace=True)
print()
print(df.isna().sum())


Index        0
Interest     0
Credit       0
Gender       0
Previous     0
Duration    70
Churn        0
dtype: int64


In [80]:
# Fill missing Value Duration

print(df.isna().sum())

Index        0
Interest     0
Credit       0
Gender       0
Previous     0
Duration    70
Churn        0
dtype: int64


In [81]:
df['Duration'].fillna(df['Duration'].median(),inplace=True)
print()
print(df.isna().sum())


Index       0
Interest    0
Credit      0
Gender      0
Previous    0
Duration    0
Churn       0
dtype: int64


In [82]:
# Convert Gender to Catgory

print(df.dtypes)

Index         int64
Interest    float64
Credit        int64
Gender      float64
Previous    float64
Duration    float64
Churn        object
dtype: object


In [83]:
print(df.dtypes)
df['Gender']=df['Gender'].astype('category')
print()
print(df.dtypes)

Index         int64
Interest    float64
Credit        int64
Gender      float64
Previous    float64
Duration    float64
Churn        object
dtype: object

Index          int64
Interest     float64
Credit         int64
Gender      category
Previous     float64
Duration     float64
Churn         object
dtype: object


In [84]:
# Convert Previous from Float to Category

print(df.dtypes)
df['Previous']=df['Previous'].astype('category')
print('**************')
print(df.dtypes)

Index          int64
Interest     float64
Credit         int64
Gender      category
Previous     float64
Duration     float64
Churn         object
dtype: object
**************
Index          int64
Interest     float64
Credit         int64
Gender      category
Previous    category
Duration     float64
Churn         object
dtype: object


In [85]:
# Convert Churn to Category and Label Encoding

print(df.dtypes)

Index          int64
Interest     float64
Credit         int64
Gender      category
Previous    category
Duration     float64
Churn         object
dtype: object


In [86]:
df['Churn']=df['Churn'].astype('category')
print(df.dtypes)

Index          int64
Interest     float64
Credit         int64
Gender      category
Previous    category
Duration     float64
Churn       category
dtype: object


In [87]:
df['Churn']=df['Churn'].cat.codes
print('***********')
print(df.dtypes)

***********
Index          int64
Interest     float64
Credit         int64
Gender      category
Previous    category
Duration     float64
Churn           int8
dtype: object


In [88]:
df

Index  Interest  Credit Gender Previous  Duration  Churn
0        0   17546.0       1    0.0      0.0      48.0      0
1        1   30085.1       3    1.0      1.0      40.0      1
2        2   16575.4       0    0.0      1.0      51.0      1
3        3   20375.4       3    0.0      0.0      23.0      1
4        4   50576.3       0    0.0      0.0      57.0      0
..     ...       ...     ...    ...      ...       ...    ...
595    595   47025.0       2    0.0      1.0      43.0      1
596    596    9672.3       0    0.0      1.0      43.0      1
597    597   15976.3       0    0.0      1.0      43.0      0
598    598   14711.8       0    1.0      0.0      29.0      0
599    599   26671.6       0    1.0      1.0      38.0      1

[600 rows x 7 columns]

In [89]:
# Create X Variable

x=df.iloc[:,1:6].values
print(x)

[[1.75460e+04 1.00000e+00 0.00000e+00 0.00000e+00 4.80000e+01]
 [3.00851e+04 3.00000e+00 1.00000e+00 1.00000e+00 4.00000e+01]
 [1.65754e+04 0.00000e+00 0.00000e+00 1.00000e+00 5.10000e+01]
 ...
 [1.59763e+04 0.00000e+00 0.00000e+00 1.00000e+00 4.30000e+01]
 [1.47118e+04 0.00000e+00 1.00000e+00 0.00000e+00 2.90000e+01]
 [2.66716e+04 0.00000e+00 1.00000e+00 1.00000e+00 3.80000e+01]]


In [90]:
# Create Y Variale

y=df.iloc[:,6].values
print(y)

[0 1 1 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 1 0 1 1 1 1 1 1 1 1 1 1 0 1 0 1 1 1
 1 1 1 1 1 0 1 1 1 1 1 1 0 0 0 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0
 1 0 1 1 1 0 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 0 1 1 1 1 1 1 1 1 1 0 1 1 1 1
 0 1 1 1 1 0 1 0 1 0 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 0 1 1
 0 1 1 1 0 1 0 1 1 1 1 1 1 0 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0
 1 0 1 1 1 1 0 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 0 1 0 1
 1 1 1 1 1 1 1 0 1 1 1 1 0 1 1 1 0 1 0 1 1 1 0 1 0 1 1 1 1 1 1 0 1 1 1 1 1
 0 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1 0 1 1 0 1 1 0 1 1 0 1 1 0 1
 1 0 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 0 1 0 1 1 1 0
 1 1 0 0 0 1 1 1 0 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 1 1 0
 1 1 0 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1 0 1 1 0 0 0 0 0 1 1 0 1 0 1 0 1 1 1
 1 0 0 1 1 1 1 1 1 0 0 0 1 1 0 1 1 1 1 0 0 1 1 0 1 1 1 0 1 0 0 1 1 0 1 1 1
 1 1 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1
 1 1 0 1 1 0 1 0 0 0 1 0 

In [91]:
# Standardization of X variable (Independent)
from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
x=sc_x.fit_transform(x)
print(x)

[[-0.83481117 -0.01104933 -0.96398156 -0.97043679  0.39357468]
 [ 0.20322955  1.88312118  1.03736424  1.03046381 -0.19900953]
 [-0.91516162 -0.95813458 -0.96398156  1.03046381  0.61579376]
 ...
 [-0.9647577  -0.95813458 -0.96398156  1.03046381  0.02320955]
 [-1.06943845 -0.95813458  1.03736424 -0.97043679 -1.01381282]
 [-0.07935469 -0.95813458  1.03736424  1.03046381 -0.34715558]]


In [92]:
# Create PCA with n_components=None

from sklearn.decomposition import PCA
pca=PCA(n_components=None)
PCA_X=pca.fit_transform(x)
print(pd.DataFrame(PCA_X))

            0         1         2         3         4
0   -0.389348 -1.263066  0.561508 -0.217232 -0.783283
1    0.258535  2.122143  0.938872 -0.534113  0.167161
2    0.008022 -0.424435 -0.082947  1.681945 -1.053486
3   -1.330230 -0.276444  2.208619 -0.862935  0.660123
4    1.864882 -1.788824 -0.570752 -0.196370  0.692477
..        ...       ...       ...       ...       ...
595  1.504013  0.377072  1.179921  0.631916  1.118015
596 -0.791650 -0.348038  0.038977  1.813712 -1.039632
597 -0.432636 -0.359121 -0.021943  1.753198 -0.670900
598 -1.813000 -0.205058 -1.207329 -0.564423 -0.046633
599 -0.290127  0.958035 -1.267196  0.749886  0.112675

[600 rows x 5 columns]


In [93]:
# PCA Percentage

print(pca.explained_variance_ratio_)

[0.33943997 0.20168854 0.20083191 0.18998087 0.06805872]


In [94]:
# Create PCA with n_components=2

from sklearn.decomposition import PCA
pca=PCA(n_components=2)
PCA_X=pca.fit_transform(x)
print(pd.DataFrame(PCA_X))

            0         1
0   -0.389348 -1.263066
1    0.258535  2.122143
2    0.008022 -0.424435
3   -1.330230 -0.276444
4    1.864882 -1.788824
..        ...       ...
595  1.504013  0.377072
596 -0.791650 -0.348038
597 -0.432636 -0.359121
598 -1.813000 -0.205058
599 -0.290127  0.958035

[600 rows x 2 columns]


In [95]:
# PCA Percentage

print(pca.explained_variance_ratio_)

[0.33943997 0.20168854]


In [96]:
# Train Test Split

from sklearn.model_selection import train_test_split
PCA_X_train,PCA_X_test,y_train,y_test=train_test_split(PCA_X,y,test_size=0.2,random_state=42)
print(PCA_X.shape)
print(PCA_X_train.shape)
print(PCA_X_test.shape)

(600, 2)
(480, 2)
(120, 2)


In [97]:
# Display X Train as Data Frame

print(pd.DataFrame(PCA_X_train))

            0         1
0    1.738955 -0.502162
1    0.204813  0.417182
2   -0.468288  0.944145
3   -0.226301 -0.307319
4    0.345016  1.734410
..        ...       ...
475 -2.598207 -0.129107
476  1.405671  0.834581
477  3.120727 -1.096250
478 -1.734504  1.895565
479 -0.723088  0.945547

[480 rows x 2 columns]


In [98]:
# Create logistic model PCA applied variables

from sklearn.linear_model import LogisticRegression
logmodel=LogisticRegression()
logmodel=logmodel.fit(PCA_X_train,y_train)
print(logmodel)

LogisticRegression()


In [99]:
# Prediction 

y_pred=logmodel.predict(PCA_X_test)
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [100]:
# Confusion_Matrix

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[ 0 28]
 [ 0 92]]


In [101]:
# Accuracy Score

print(accuracy_score(y_test,y_pred))

0.7666666666666667


In [102]:
# Create Decision Tree model PCA applied variables

from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
dt=dt.fit(PCA_X_train,y_train)
print(dt)

DecisionTreeClassifier()


In [103]:
# Prediction

y_pred=dt.predict(PCA_X_test)
print(y_pred)

[1 0 0 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 0 1 0 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 1 1 1 0 0 1 1 0 1
 1 1 0 1 0 0 1 1 1 0 1 0 1 0 0 1 0 0 1 1 1 0 1 1 1 0 1 1 1 1 1 1 0 1 1 1 1
 1 1 1 1 0 0 1 1 1]


In [104]:
# Confusion_matrix and Accuracy Score

print(accuracy_score(y_test,y_pred))
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(cm) 

0.6166666666666667
[[ 6 22]
 [24 68]]


In [105]:
(68+6)/120

0.6166666666666667

In [106]:
# Create model with out PCA

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [107]:
# Dsiplay x_train as data frame

pd.DataFrame(x_train)

0         1         2         3         4
0    1.951560 -0.958135  1.037364 -0.970437  1.134305
1   -0.282963  0.936036 -0.963982  1.030464  0.023210
2   -0.559942 -0.958135  1.037364  1.030464 -0.124937
3    0.000000 -0.958135 -0.963982  1.030464 -0.643448
4    0.599088  0.936036  1.037364  1.030464 -0.347156
..        ...       ...       ...       ...       ...
475 -1.619880 -0.958135  1.037364 -0.970437 -1.606397
476  1.573136 -0.958135  1.037364  1.030464  0.467648
477  2.741595  0.936036 -0.963982 -0.970437  1.800962
478 -1.315713  0.936036  1.037364  1.030464 -1.458251
479 -1.004196 -0.958135  1.037364  1.030464 -0.050863

[480 rows x 5 columns]

In [108]:
# Create logistic model without PCA

from sklearn.linear_model import LogisticRegression
logmodelNOPCA=LogisticRegression()
logmodelNOPCA=logmodelNOPCA.fit(x_train,y_train)
print(logmodelNOPCA)

LogisticRegression()


In [109]:
# Prdiction

y_pred=logmodelNOPCA.predict(x_test)
print(y_pred)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1]


In [110]:
# Confusion matrix

cm=confusion_matrix(y_test,y_pred)
print(cm)

[[ 0 28]
 [ 0 92]]


In [111]:
# Accuracy Score
print(accuracy_score(y_test,y_pred))

0.7666666666666667


In [112]:
# Create Decision Tree without PCA

from sklearn.tree import DecisionTreeClassifier
dtnopca=DecisionTreeClassifier()
dtnopca=dt.fit(x_train,y_train)
print(dtnopca)

DecisionTreeClassifier()


In [113]:
# Prediction 

y_pred=dtnopca.predict(x_test)
y_pred

array([1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 1], dtype=int8)

In [114]:
# Confusion_matrix and Accuracy Score

print(accuracy_score(y_test,y_pred))
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(cm)

0.6333333333333333
[[ 7 21]
 [23 69]]


In [115]:
(4+71)/120

0.625

In [116]:
# OK Prajwal 😄